### ISSUE TITLE
Both UVC & UAC getting start doesn't want to compile for ESP32-S3

### ISSUE THREAD

**Issue by joyel24** [esp-arduino-libs/ESP32_USB_Stream#2]
```
Compiling core...
/usr/bin/env bash -c "echo -DARDUINO_CORE_BUILD > '/var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/file_opts'"
Using precompiled core: /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_cache_245035/core/core_4b6716b556e99d089fdbecee560f77aa.a
/usr/bin/env bash -c ": > '/var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/file_opts'"
Linking everything together...
/Users/joel/Library/Arduino15/packages/esp32/tools/esp-xs3/2302/bin/xtensa-esp32s3-elf-g++ @/Users/joel/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32s3/flags/ld_flags @/Users/joel/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32s3/flags/ld_scripts -Wl,--Map=/var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/GettingStartUVC.ino.map -L/Users/joel/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32s3/lib -L/Users/joel/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32s3/ld -L/Users/joel/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32s3/qio_qspi -Wl,--wrap=esp_panic_handler -Wl,--start-group /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/sketch/GettingStartUVC.ino.cpp.o /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/libraries/ESP32_USB_STREAM/USB_STREAM.cpp.o /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/libraries/ESP32_USB_STREAM/original/descriptor.c.o /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/libraries/ESP32_USB_STREAM/original/usb_host_helpers.c.o /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/libraries/ESP32_USB_STREAM/original/usb_stream.c.o /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_cache_245035/core/core_4b6716b556e99d089fdbecee560f77aa.a @/Users/joel/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32s3/flags/ld_libs -Wl,--end-group -Wl,-EL -o /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/GettingStartUVC.ino.elf
/Users/joel/Library/Arduino15/packages/esp32/tools/esp-xs3/2302/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/libraries/ESP32_USB_STREAM/original/usb_stream.c.o:(.literal.usb_streaming_start+0x34): undefined reference to `mps_limits_default'
/Users/joel/Library/Arduino15/packages/esp32/tools/esp-xs3/2302/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: /var/folders/kg/wxdt75kd0lvcb91rmqvck1f40000gn/T/arduino_build_15691/libraries/ESP32_USB_STREAM/original/usb_stream.c.o:(.literal.usb_streaming_start+0x6c): undefined reference to `mps_limits_bias_rx'
collect2: error: ld returned 1 exit status
```

Highlights on 2 errors:
undefined reference to 'mps_limits_bias_rx'
undefined reference to 'mps_limits_default'

**Comment by Criminal-9527** [comment]
我也遇到了同样的问题：
```
undefined reference to `mps_limits_default'
undefined reference to `mps_limits_bias_rx'
```
我的板子是ESP32-S3-LCD-EV-Board，在usb->start()这个函数调用的时候出现了这个问题
奇怪的是我发现这个问题是在将arduino的开发板管理器中将esp32板子的版本号升级到v3.0.2之后出现的这个问题，之前我用v2.x跑的时候是没问题的，可能是升级后改变了函数接口

**Comment by Criminal-9527** [comment]
@alibukharai @Lzw655 ,抱歉以这样的方式at你们，但我真的很需要这个头文件，

**Comment by joyel24** [comment]
I'll do the same test later with the UVC & UAC getting start example with the same module and same usb peripheral to see how it works now...

**Comment by jiesou** [comment]
> 我也遇到了同样的问题：
> 
> ```
> undefined reference to `mps_limits_default'
> undefined reference to `mps_limits_bias_rx'
> ```
> 
> 我的板子是ESP32-S3-LCD-EV-Board，在usb->start()这个函数调用的时候出现了这个问题 奇怪的是我发现这个问题是在将arduino的开发板管理器中将esp32板子的版本号升级到v3.0.2之后出现的这个问题，之前我用v2.x跑的时候是没问题的，可能是升级后改变了函数接口

```
Backtrace: 0x4203a0cc:0x3fced510 0x4203b87b:0x3fced550 0x4200df0a:0x3fced570 0x4200f6ca:0x3fced690
  #0  0x4203a0cc in _buffer_fill_ctrl at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/usb/hcd_dwc.c:2096
      (inlined by) _buffer_fill at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/usb/hcd_dwc.c:2237
  #1  0x4203b87b in hcd_urb_enqueue at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/usb/hcd_dwc.c:2597
  #2  0x4200df0a in _uvc_uac_device_enum at .pio/libdeps/esp32cam/ESP32_USB_STREAM/src/original/usb_stream.c:3142
  #3  0x4200f6ca in _usb_processing_task at .pio/libdeps/esp32cam/ESP32_USB_STREAM/src/original/usb_stream.c:3371
```

<details>
  <summary>我的代码</summary>

```cpp
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "esp_err.h"
#include "esp_log.h"
#include "original/include/usb_stream.h"
#include "freertos/semphr.h"
#include "esp_camera.h"
#include <WiFi.h>

// #include "CamServer.h"

// UVC Camera 信号量
static SemaphoreHandle_t sem_usb_done = NULL;
static SemaphoreHandle_t sem_xfer_done = NULL;
static camera_fb_t s_fb = {0};
static bool xfer_connect = false;

void camera_frame_cb(uvc_frame_t *frame, void *ptr)
{
  Serial.printf("Received frame: %dx%d, size: %zu bytes, sequence: %u\n",
                frame->width, frame->height, frame->data_bytes, frame->sequence);
  if (frame->frame_format == UVC_FRAME_FORMAT_MJPEG)
  {
    // 填充 camera_fb_t 结构体
    s_fb.buf = static_cast<uint8_t *>(frame->data);
    s_fb.len = frame->data_bytes;
    s_fb.width = frame->width;
    s_fb.height = frame->height;
    s_fb.format = PIXFORMAT_JPEG;
    s_fb.timestamp.tv_sec = frame->sequence;

    // 通知 WiFi 传输线程有新帧可用
    xSemaphoreGive(sem_usb_done);

    // 等待传输完成（如果有连接）
    if (xfer_connect)
    {
      if (xSemaphoreTake(sem_xfer_done, pdMS_TO_TICKS(1000)) == pdFALSE)
      {
        xfer_connect = false; // 超时，断开连接
      }
    }
  }
}

const char *ssid = "CMCC-xxxx";
const char *password = "xxxx";

void setup()
{
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Serial.println();

  // 创建 UVC Camera 信号量
  sem_usb_done = xSemaphoreCreateBinary();
  sem_xfer_done = xSemaphoreCreateBinary();

  // 配置 USB 摄像头
  uint8_t *xfer_buffer_a = (uint8_t *)malloc(88 * 1024); // 88KB

  uint8_t *xfer_buffer_b = (uint8_t *)malloc(88 * 1024); // 88KB

  uint8_t *frame_buffer = (uint8_t *)malloc(88 * 1024); // 88KB

  uint16_t uvc_frame_w = 480;
  uint16_t uvc_frame_h = 480;

  // 配置 UVC 参数
  uvc_config_t uvc_config = {
      .frame_width = uvc_frame_w,
      .frame_height = uvc_frame_h,
      .frame_interval = FRAME_INTERVAL_FPS_30,
      .xfer_buffer_size = 88 * 1024, // 88KB
      .xfer_buffer_a = xfer_buffer_a,
      .xfer_buffer_b = xfer_buffer_b,
      .frame_buffer_size = 88 * 1024, // 88KB
      .frame_buffer = frame_buffer,
      .frame_cb = &camera_frame_cb, // 核心回调函数
      .frame_cb_arg = NULL,
  };

  // 配置 UVC 流
  ESP_ERROR_CHECK(uvc_streaming_config(&uvc_config));

  // 启动 USB 流处理
  ESP_ERROR_CHECK(usb_streaming_start());

  Serial.println("USB device connected!");

  WiFi.begin(ssid, password);
  WiFi.setSleep(false);

  Serial.print("WiFi connecting");
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(50);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");

  Serial.print("Camera Ready! IP:");
  Serial.println(WiFi.localIP());

  camServer.init();
}

camera_fb_t *esp_camera_fb_get()
{
  xSemaphoreTake(sem_usb_done, portMAX_DELAY);
  return &s_fb;
}

void esp_camera_fb_return(camera_fb_t *fb)
{
  xfer_connect = true;
  xSemaphoreGive(sem_xfer_done);
  return;
}

camera_fb_t *fb = NULL;
unsigned long lastCaptureTime = 0;
void loop()
{
  // camServer.update(); // 必须每次都调用

  unsigned long now = millis();
  if (now - lastCaptureTime > 100)
  { // 控制 10 帧
    fb = esp_camera_fb_get();
    if (fb)
    {
      // camServer.broadcastImg(fb->buf, fb->len);
      esp_camera_fb_return(fb);
    }
    lastCaptureTime = now;
  }
}
```
</details>

我使用的也是 ESP32-S3-LCD-EV-Board v1.5，依旧不知道这个库怎么用，方便把你的 demo 贴上来吗

**Comment by jiesou** [comment]
完全使用
https://github.com/esp-arduino-libs/ESP32_USB_Stream/blob/master/examples/GettingStartUVC/GettingStartUVC.ino
也是一样的错误
